### ISSUE TITLE
文档挂了

### ISSUE THREAD

**Issue by dmf-code** [betterde/ects#11]
文档没有了，希望重新更新一下

**Comment by jinrenjie** [comment]
文档是放在 GitHub Pages 上的，可能需要科学上网才能访问。

**Comment by dmf-code** [comment]
![image](https://user-images.githubusercontent.com/22268578/91512695-299d9680-e915-11ea-9950-0d308f7b5e2b.png)
这个不像是要科学上网吧，直接404了

**Comment by dmf-code** [comment]
谢谢，确实是要科学上网才行
