### ISSUE TITLE
go build -o ects main.go 失败

### ISSUE THREAD

**Issue by 54huige** [betterde/ects#17]
# github.com/betterde/ects/internal/actuator
internal\actuator\shell.go:32:18: cmd.SysProcAttr.Credential undefined (type *syscall.SysProcAttr has no field or method Credential)
internal\actuator\shell.go:58:39: undefined: syscall.Credential
internal\actuator\shell.go:65:10: undefined: syscall.Credential

**Comment by 54huige** [comment]
是不是 windows下面 不好使？大佬在不

**Comment by jinrenjie** [comment]
@54huige Windows 没有兼容，这个问题有空我排查一下

**Comment by 54huige** [comment]
**感谢  我在网上看到 貌似 因为go版本不同导致的 我是go 1.14.4

听说改成了这样 具体是不是我也不清楚  等大佬处理了**
```
// cmd.SysProcAttr.Credential = &syscall.Credential{Uid: uint32(1), Gid: uint32(1)}

cmd.SysProcAttr.UidMappings = []syscall.SysProcIDMap{
{ContainerID: 5001, HostID: syscall.Getuid(), Size: 1},
}
cmd.SysProcAttr.GidMappings = []syscall.SysProcIDMap{
{ContainerID: 5001, HostID: syscall.Getgid(), Size: 1},
}
```
